/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package R16A_Group_6_A2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
}
