/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package R16A_Group_6_A2;

public class App {

    public static void main(String[] args) {
        UserData userData = new UserData();
        new LogInPage(userData);
    }
}
